# Configuration
# Need help? Join our Discord, https://kyle-hosting.xyz/discord/

ConfigVersion: ${version}

BotToken: "BOTTOKEN"

# Chat Config
Channels: {"global": "000000000000000000"}
DiscordConsoleChannelId: "000000000000000000"
DiscordInviteLink: "https://discord.gg/changethisintheconfig.yml"
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelRequireLinkedAccount: false

# Game Information
DiscordGameStatus: ["playing Minecraft"]
DiscordOnlineStatus: ONLINE
StatusUpdateRateInMinutes: 1


# Chat channel player list command
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "players"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true

# Discord Responses
DiscordCannedResponses: {"!ip": "ch.kyle-hosting.xyz:25597", "!site": "https://kyle-hosting.xyz"}

# Webhooks
Experiment_WebhookChatMessageDelivery: true
Experiment_WebhookChatMessageUsernameFormat: "%displayname%"
Experiment_WebhookChatMessageFormat: "%message%"
Experiment_WebhookChatMessageUsernameFromDiscord: true
Experiment_WebhookChatMessageAvatarFromDiscord: true
Experiment_WebhookChatMessageUsernameFilters: {}
AvatarUrl: ""


# Reserializer
Experiment_MCDiscordReserializer_ToDiscord: false
Experiment_MCDiscordReserializer_ToMinecraft: false
Experiment_MCDiscordReserializer_InBroadcast: false

# Plugin hooks
DisabledPluginHooks: []
VentureChatBungee: false
EnablePresenceInformation: false
UseModernPaperChatEvent: false

Experiment_JdbcAccountLinkBackend: "jdbc:mysql://HOST:PORT/DATABASE?autoReconnect=true&useSSL=false"
Experiment_JdbcTablePrefix: "discordsrv"
Experiment_JdbcUsername: "username"
Experiment_JdbcPassword: "password"

# Chat channel information
DiscordChatChannelTruncateLength: 256
DiscordChatChannelTranslateMentions: true
DiscordChatChannelAllowedMentions: [user, channel, emote]
DiscordChatChannelEmojiBehavior: "name"
DiscordChatChannelEmoteBehavior: "name"
DiscordChatChannelPrefixRequiredToProcessMessage: ""
DiscordChatChannelPrefixActsAsBlacklist: false
DiscordChatChannelRolesAllowedToUseColorCodesInChat: ["Developer", "Owner", "Admin", "Moderator"]
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
DiscordChatChannelBlockBots: false
DiscordChatChannelBlockWebhooks: true
DiscordChatChannelBlockedIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelBlockedRolesAsWhitelist: false
DiscordChatChannelBlockedRolesIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelRolesSelectionAsWhitelist: false
DiscordChatChannelRolesSelection: ["Don't show me!", "Misc role"]
DiscordChatChannelRoleAliases: {"Developer": "Dev"}

# Console channel information
DiscordConsoleChannelLogRefreshRateInSeconds: 5
DiscordConsoleChannelUsageLog: "Console-%date%.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands: ["?", "op", "deop", "execute"]
DiscordConsoleChannelFilters: {".*(?i)async chat thread.*": "", ".*There are \\d+ (?:of a max of|out of maximum) \\d+ players online.*": ""}
DiscordConsoleChannelLevels: [info, warn, error]
DiscordConsoleChannelUseCodeBlocks: true
DiscordConsoleChannelBlockBots: true

# Chat channel command execute command
DiscordChatChannelConsoleCommandEnabled: true
DiscordChatChannelConsoleCommandNotifyErrors: true
DiscordChatChannelConsoleCommandPrefix: "!c"
DiscordChatChannelConsoleCommandRolesAllowed: ["Owner"]
DiscordChatChannelConsoleCommandWhitelist: ["say", "lag", "tps"]
DiscordChatChannelConsoleCommandWhitelistBypassRoles: ["Owner"]
DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: false
DiscordChatChannelConsoleCommandExpiration: 0
DiscordChatChannelConsoleCommandExpirationDeleteRequest: true

# Chat channel blacklisted phrases & regex
DiscordChatChannelGameFilters: {}
DiscordChatChannelDiscordFilters: {".*Online players \\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}

# Channel topic updater settings
ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true
ChannelTopicUpdaterRateInMinutes: 10

# Channel Updater
ChannelUpdater:
  - ChannelId: "0000000000000000"
    Format: "%playercount% players online"
    ShutdownFormat: "Server is offline"
    UpdateInterval: 10
  - ChannelId: "0000000000000000"
    Format: "Current TPS: %tps%"
    ShutdownFormat: "Server is offline"
    UpdateInterval: 10

# Minecraft to Discord account linking
MinecraftDiscordAccountLinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountUnlinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Linked"
MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: false
MinecraftDiscordAccountLinkedUsePM: true
MinecraftDiscordAccountLinkedMessageDeleteSeconds: 0

# Server watchdog
ServerWatchdogEnabled: true
ServerWatchdogTimeout: 30
ServerWatchdogMessageCount: 3



# Debug information
# Available Debug categories:
# MINECRAFT_TO_DISCORD  - Messages coming from Minecraft
# DISCORD_TO_MINECRAFT  - Messages coming from Discord
# GROUP_SYNC            - Group synchronization
# PRESENCE              - The bot's game status or presence
# VOICE                 - The voice module (see voice.yml)
# REQUIRE_LINK          - The require link to join module (see linking.yml)
# NICKNAME_SYNC         - Nickname synchronization
# ALERTS                - Alerts (see alerts.yml)
# WATCHDOG              - The watchdog
# BAN_SYNCHRONIZATION   - Ban synchronization
# LP_CONTEXTS           - LuckPerm's contexts
# ACCOUNT_LINKING       - discord/minecraft account linking
# UNCATEGORIZED         - Anything not in any of the above categories
# ALL                   - All the above categories (including UNCATEGORIZED)
# JDA                   - JDA's debug messages
# JDA_REST_ACTIONS      - For debugging JDA's rest actions
# CALLSTACKS            - Displays the stack trace for DiscordSRV debug calls
# Ex. "Debug: [GROUP_SYNC, PRESENCE]"
#
Debug: []

# Other
CancelConsoleCommandIfLoggingFailed: true
ForcedLanguage: none
ForceTLSv12: true
NoopHostnameVerifier: false
MaximumAttemptsForSystemDNSBeforeUsingFallbackDNS: 3
TimestampFormat: EEE, d. MMM yyyy HH:mm:ss z
DateFormat: yyyy-MM-dd
Timezone: default
MinecraftMentionSound: true

# HTTP proxy used for connecting to the Discord API
ProxyHost: "example.com"
ProxyPort: 1234
ProxyUser: "USERNAME"
ProxyPassword: "PASSWORD"